add functions to add, delete and update todo list tasks in different …
joyapisi/To-Do-List pull request #2
Opened 2023-03-29 15:10 UTC by joyapisi

## What I Have Done🧨 :
`add CRUD (create, read, update, delete) methods`
-Add new folder ./modules is ./src folder
-add 3 files in ./modules which have the functionalities to add, delete and update to do list items

2023-03-30 12:39 UTC, thecodechaser requested changes
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @joyapisi👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
- No linter errors. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- GitHub flow is followed. :heavy_check_mark:
- PR has a good title and summary. ✔️

<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Required Changes ♻️

- [ ] In the README file please add steps to set up and run the project, It will make the README file more professional. Example: `npm install` `npm run start`.

- [ ] Check the comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-30 12:39 UTC, thecodechaser commented on src/modules/add-task.js
> +
- [ ] When I'm trying to add a new task, I'm getting the below error. Please make sure to fix this issue and users should be able to add tasks without any errors. Also, make sure other functionalities(remove and edit) also work as expected.

![image](https://user-images.githubusercontent.com/83803414/228835454-12c4584c-34d8-40e0-b586-3f2f7953390b.png)

2023-03-30 12:39 UTC, thecodechaser commented on src/index.js
> +// }
- [ ] Please remove the commented code from the files, It's not good practice to leave commented code.

2023-03-30 12:39 UTC, thecodechaser commented on src/index.js
> +// retrieveToDoList();
- [ ] Please remove the commented code from the files, It's not good practice to leave commented code.

2023-04-01 14:59 UTC, prolajumokeoni approved these changes
Hi @joyapisi 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
## Highlights
 - Changes requested have been implemented 👏🏿 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- Kindly update instructions in readme on how to start the app in your setup section like `npm start` 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-01 16:44 UTC, joyapisi commented
Add functions to add, delete and update items in Todo list

2023-04-01 16:44 UTC, merged